/**
 * Amoga Design System — Central Barrel Export
 *
 * Single source of truth for all reusable tokens, core UI primitives,
 * business components, and page templates.
 */

// ── Design Tokens ────────────────────────────────────────────────────────────
export * from './tokens'

// ── Core UI Components (shadcn/ui primitives) ────────────────────────────────
export { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './components/ui/accordion'
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogOverlay, AlertDialogPortal, AlertDialogTitle, AlertDialogTrigger } from './components/ui/alert-dialog'
export { Alert, AlertDescription, AlertTitle } from './components/ui/alert'
export { AspectRatio } from './components/ui/aspect-ratio'
export { Avatar, AvatarFallback, AvatarImage } from './components/ui/avatar'
export { Badge, badgeVariants } from './components/ui/badge'
export { Breadcrumb, BreadcrumbEllipsis, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from './components/ui/breadcrumb'
export { Button, buttonVariants } from './components/ui/button'
export { ButtonGroup } from './components/ui/button-group'
export { Calendar } from './components/ui/calendar'
export { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from './components/ui/card'
export { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from './components/ui/carousel'
export { ChartContainer, ChartLegend, ChartLegendContent, ChartStyle, ChartTooltip, ChartTooltipContent } from './components/ui/chart'
export { Checkbox } from './components/ui/checkbox'
export { Collapsible, CollapsibleContent, CollapsibleTrigger } from './components/ui/collapsible'
export { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from './components/ui/command'
export { ContextMenu, ContextMenuCheckboxItem, ContextMenuContent, ContextMenuGroup, ContextMenuItem, ContextMenuLabel, ContextMenuPortal, ContextMenuRadioGroup, ContextMenuRadioItem, ContextMenuSeparator, ContextMenuShortcut, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuTrigger } from './components/ui/context-menu'
export { DatePicker as DatePickerPrimitive } from './components/ui/date-picker'
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger } from './components/ui/dialog'
export { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerOverlay, DrawerPortal, DrawerTitle, DrawerTrigger } from './components/ui/drawer'
export { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from './components/ui/dropdown-menu'
export { Empty } from './components/ui/empty'
export { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from './components/ui/form'
export { HoverCard, HoverCardContent, HoverCardTrigger } from './components/ui/hover-card'
export { Input } from './components/ui/input'
export { InputGroup, InputGroupInput, InputGroupText } from './components/ui/input-group'
export { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from './components/ui/input-otp'
export { Kbd } from './components/ui/kbd'
export { Label } from './components/ui/label'
export { Menubar, MenubarCheckboxItem, MenubarContent, MenubarGroup, MenubarItem, MenubarLabel, MenubarMenu, MenubarPortal, MenubarRadioGroup, MenubarRadioItem, MenubarSeparator, MenubarShortcut, MenubarSub, MenubarSubContent, MenubarSubTrigger, MenubarTrigger } from './components/ui/menubar'
export { NavigationMenu, NavigationMenuContent, NavigationMenuIndicator, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, NavigationMenuViewport } from './components/ui/navigation-menu'
export { Pagination, PaginationContent, PaginationEllipsis, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from './components/ui/pagination'
export { Popover, PopoverContent, PopoverTrigger } from './components/ui/popover'
export { Progress } from './components/ui/progress'
export { RadioGroup, RadioGroupItem } from './components/ui/radio-group'
export { ResizableHandle, ResizablePanel, ResizablePanelGroup } from './components/ui/resizable'
export { ScrollArea, ScrollBar } from './components/ui/scroll-area'
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectScrollDownButton, SelectScrollUpButton, SelectSeparator } from './components/ui/select'
export { Separator } from './components/ui/separator'
export { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetOverlay, SheetPortal, SheetTitle, SheetTrigger } from './components/ui/sheet'
export { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger, useSidebar } from './components/ui/sidebar'
export { Skeleton } from './components/ui/skeleton'
export { Slider } from './components/ui/slider'
export { Sonner } from './components/ui/sonner'
export { Spinner } from './components/ui/spinner'
export { Switch } from './components/ui/switch'
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from './components/ui/table'
export { Tabs, TabsContent, TabsList, TabsTrigger } from './components/ui/tabs'
export { Textarea } from './components/ui/textarea'
export { Toggle, toggleVariants } from './components/ui/toggle'
export { ToggleGroup, ToggleGroupItem } from './components/ui/toggle-group'
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './components/ui/tooltip'

// ── Reusable Business Components ─────────────────────────────────────────────
export { ConfirmDialog } from './components/business/confirm-dialog'
export { PasswordInput } from './components/business/password-input'
export { SignOutDialog } from './components/business/sign-out-dialog'
export { ThemeSwitch } from './components/business/theme-switch'
export { ThemeSelector } from './components/business/theme-selector'
export { SelectDropdown } from './components/business/select-dropdown'
export { LongText } from './components/business/long-text'
export { Search } from './components/business/search'
export { Stats01 } from './components/business/stats-01'
export { DatePicker } from './components/business/date-picker'
export { QRCodeDisplay } from './components/business/qr-code-display'

// ── Reusable Page Templates ──────────────────────────────────────────────────
export { AppHeader } from './templates/app-header'
export { AppLogo } from './templates/app-logo'
export { AppSidebar } from './templates/app-sidebar'
export { AppTitle } from './templates/app-title'
export { AuthenticatedLayout } from './templates/authenticated-layout'
export { Header } from './templates/header'
export { Main } from './templates/main'
export { NavGroup } from './templates/nav-group'
export { NavUser } from './templates/nav-user'
export { SidebarSearch } from './templates/sidebar-search'
export { TeamSwitcher } from './templates/team-switcher'
export { TopNav } from './templates/top-nav'
export { sidebarData } from './templates/data/sidebar-data'
